#--- Game Launchers ---
choco install -y cemu
choco install -y dolphin
choco install -y ds4windows
choco install -y epicgameslauncher
choco install -y goggalaxy
choco install -y minecraft-launcher
choco install -y origin
choco install -y steam
choco install -y steam-cleaner
choco install -y steamlibrarymanager.portable
choco install -y twitch
choco install -y uplay
