#--- PowerShell Tools ---
choco install -y checksum
choco install -y curl
choco install -y llvm
choco install -y psutils
choco install -y rsync
choco install -y unzip
choco install -y winscreenfetch
choco install -y zip
